# Generated by Django 5.1 on 2024-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_name', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('Folder_Id', models.IntegerField(default=0)),
                ('FolderName', models.CharField(default='UnKnown Album', max_length=225)),
            ],
        ),
    ]
