# Generated by Django 5.1 on 2024-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folder_Id', models.IntegerField(default=0)),
                ('FolderName', models.CharField(default='UnKnown Album', max_length=225)),
            ],
        ),
    ]
