# Generated by Django 5.1 on 2024-09-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0002_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='Folder_Id',
        ),
    ]
