# Generated by Django 5.1 on 2024-09-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayer', '0003_remove_folder_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='FolderName',
        ),
    ]
